<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVpx6Z9p\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVpx6Z9p/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVpx6Z9p.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVpx6Z9p\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVpx6Z9p\App_KernelDevDebugContainer([
    'container.build_hash' => 'Vpx6Z9p',
    'container.build_id' => 'f5dd05c1',
    'container.build_time' => 1714203835,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVpx6Z9p');
