<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZDuz28F\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZDuz28F/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZDuz28F.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZDuz28F\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZDuz28F\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZDuz28F',
    'container.build_id' => 'dbf8d6f7',
    'container.build_time' => 1714090850,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZDuz28F');
